mysite/mysite/urls.py
from django.urls import include, path
from django.contrib import admin
from django.views.generic import RedirectView

urlpatterns = [
    path('todo/', include('todo.urls')),
  
    path('admin/', admin.site.urls),
    path('',  RedirectView.as_view(url='/todo/')),
]

mysite/todo/urls.py
from django.urls import path

from . import views

app_name = 'todo'

urlpatterns = [
    path('', views.index, name='index'),
    path('create', views.create, name='create'),
    path('<int:id>/delete', views.delete, name='delete'),
]

mysite/todo/models.py
from django.db import models


class Post(models.Model):
    body = models.CharField(max_length=200)
    
    

mysite/todo/forms.py
from django import forms

from .models import Post

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['body',]

mysite/todo/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from .models import Post
from .forms import PostForm

# Create your views here.
def index(request):
    posts = Post.objects.all()
    form = PostForm()
    context = {'posts': posts, 'form': form, }
    return render(request, 'todo/index.html', context)
    
def create(request):
    form = PostForm(request.POST)
    form.save(commit=True)
    return HttpResponseRedirect(reverse('todo:index'))

def delete(request, id=None):
    post = get_object_or_404(Post, pk=id)
    post.delete()
    return HttpResponseRedirect(reverse('todo:index'))

mysite/todo/templates/todo/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
    <head>
        <title>ลงชื่อเข้าร่วมกิจกรรม</title>
        <!-- CSS And JavaScript -->
        <link rel="stylesheet" href="//fonts.googleapis.com/css?family=Roboto:300,300italic,700,700italic">
        <link rel="stylesheet" href="//cdn.rawgit.com/necolas/normalize.css/master/normalize.css">
        <link rel="stylesheet" href="//cdn.rawgit.com/milligram/milligram/master/dist/milligram.min.css">
        <link rel="stylesheet" href="{% static 'css/todo.css' %}">
        
        <style>
            body{
                background-color:#6699ff
            }
           .container{
                 background-color: #e6eeff 
            }
        </style>
    </head> 
    <body>
        <div class="container">
            {% block content %}
            {% endblock %}
        </div>
    </body>
</html>

mysite/todo/templates/todo/index.html
{% extends 'todo/base.html' %}

{% block content %}
    
    <h1>ลงทะเบียนเข้าร่วมกิจกรรม "COE Tutor"</h1>

    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    <form action="{% url 'todo:create' %}" method="post">
        {% csrf_token %}
        <!-- Todo Name -->
        
        <div class="form-group">
            <label for="todo" class="col-sm-3 control-label">รายชื่อ</label>
            <div class="col-sm-6">
                {{ form.body }}
            </div>
          
            

        <!-- Add Todo Button -->
        
        <div class="form-group">
            <div class="col-sm-offset-3 col-sm-6">
                <button type="submit" class="btn btn-default">
                    <i class="fa fa-plus"></i> เพิ่มรายชื่อ
                </button>
            </div>
        </div>

    </form>
    

    <!-- Current Todos -->
    <h2>ผู้ลงทะเบียน</h2>
    <table class="table table-striped todo-table">
        <thead>
            <th>รายชื่อ</th><th>&nbsp;</th>
        </thead>

        <tbody>
            {% for post in posts %}
                <tr>
                    <!-- Todo Name -->
                    <td>
                        <div>{{ post.body }}</div>
                      
                    </td>
                   
                    <td>
                        <form action="{% url 'todo:delete' post.id %}" method="post">
                            {% csrf_token %}
                            <button>Delete</button>
                        </form>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

  
    
{% endblock %}